--Events
SELECT   
flat.ArrayValue.name							as [event name]							,
flat.ArrayValue.count							as [event count]						,
flat.ArrayValue.url								as [event uri]							,
flat.ArrayValue.urlData.base					as [event uri data base]				,
flat.ArrayValue.urlData.host					as [event uri data host]				,
A.context.custom.dimensions						as [custom attributes]					,
A.context.custom.metrics						as [custom metrics]						,
A.context.data.eventTime						as [event time]							,
A.context.data.isSynthetic						as [is synthetic]						,
A.context.data.samplingRate						as [samplingRate]						,
A.context.device								as [device]								,
A.context.device.browser						as [browser]							,
A.context.device.browserVersion					as [browser version]					,
A.context.device.deviceModel					as [device model]						,
A.context.device.deviceName						as [device name]						,
A.context.device.id								as [device id]							,
A.context.device.locale							as [device locale]						,
A.context.device.network						as [device network]						,
A.context.device.oemName						as [device oem name]					,
A.context.device.osVersion						as [device os version]					,
A.context.device.roleInstance					as [device role instance]				,
A.context.device.roleName						as [device role name]					,
A.context.device.type							as [device type]						,
A.context.location								as [location]							,
A.context.location.city							as [location city]						,
A.context.location.continent					as [location continent]					,
A.context.location.country						as [location country]					,
A.context.location.province						as [location province]					,
A.context.location.clientip						as [ip address]							,
A.context.operation.id							as [operation id]						,
A.context.operation.name						as [operation name]						,
A.context.operation.parentId					as [parent id]							,
A.context.session.id							as [session id]							,
A.context.session.isFirst						as [session is first]					,
A.context.[user].accountAcquisitionDate			as [account aquisition date]			,
A.context.[user].anonAcquisitionDate			as [annoymous aquisition date]			,
A.context.[user].anonId							as [anonymous id]						,
A.context.[user].authAcquisitionDate			as [auth aquisition date]				,
A.context.[user].isAuthenticated				as [is authenticated]					,
A.internal.data.documentVersion					as [document version]					,
A.internal.data.id								as [data id]							,
'Event'											as [eventtype]
INTO docdb
FROM events A CROSS APPLY GetElements(A.[event]) as flat


--Exceptions
SELECT 
flat.ArrayValue.assembly						as [assembly]							,
flat.ArrayValue.count							as [count]								,
flat.ArrayValue.exceptionGroup					as [exception group]					,
flat.ArrayValue.exceptionType					as [exception type]						,
flat.ArrayValue.failedUserCodeMethod			as [failed user code method]			,
flat.ArrayValue.failedUserCodeAssembly			as [failed user code assembly]			,
flat.ArrayValue.handledAt						as [handled at]							,
flat.ArrayValue.hasFullStack					as [has full stack]						,
flat.ArrayValue.id								as [id]									,
flat.ArrayValue.method							as [method]								,
flat.ArrayValue.message							as [message]							,
flat.ArrayValue.outerExceptionMessage			as [outer exception message]			,
flat.ArrayValue.outerExceptionThrownAtAssembly	as [outer exception thrown at assembly]	,
flat.ArrayValue.outerExceptionThrownAtMethod	as [outer exception thrown at method]	,
flat.ArrayValue.outerExceptionType				as [outer exception type]				,
flat.ArrayValue.outerId							as [outer id]							,
flat.ArrayValue.parsedStack 					as [parsed stack ]						,
flat.ArrayValue.stack							as [stack]								,
flat.ArrayValue.typeName  						as [type name]							,
A.context.custom.dimensions						as [custom attributes]					,
A.context.custom.metrics						as [custom metrics]						,
A.context.data.eventTime						as [event time]							,
A.context.data.isSynthetic						as [is synthetic]						,
A.context.data.samplingRate						as [samplingRate]						,
A.context.device								as [device]								,
A.context.device.browser						as [browser]							,
A.context.device.browserVersion					as [browser version]					,
A.context.device.deviceModel					as [device model]						,
A.context.device.deviceName						as [device name]						,
A.context.device.id								as [device id]							,
A.context.device.locale							as [device locale]						,
A.context.device.network						as [device network]						,
A.context.device.oemName						as [device oem name]					,
A.context.device.osVersion						as [device os version]					,
A.context.device.roleInstance					as [device role instance]				,
A.context.device.roleName						as [device role name]					,
A.context.device.type							as [device type]						,
A.context.location								as [location]							,
A.context.location.city							as [location city]						,
A.context.location.continent					as [location continent]					,
A.context.location.country						as [location country]					,
A.context.location.province						as [location province]					,
A.context.location.clientip						as [ip address]							,
A.context.operation.id							as [operation id]						,
A.context.operation.name						as [operation name]						,
A.context.operation.parentId					as [parent id]							,
A.context.session.id							as [session id]							,
A.context.session.isFirst						as [session is first]					,
A.context.[user].accountAcquisitionDate			as [account aquisition date]			,
A.context.[user].anonAcquisitionDate			as [annoymous aquisition date]			,
A.context.[user].anonId							as [anonymous id]						,
A.context.[user].authAcquisitionDate			as [auth aquisition date]				,
A.context.[user].isAuthenticated				as [is authenticated]					,
A.internal.data.documentVersion					as [document version]					,
A.internal.data.id								as [data id]							,
'Exception'										as [eventtype]
INTO docdb
FROM exceptions A CROSS APPLY GetElements(A.[basicexception]) as flat

--Trace
SELECT   
flat.ArrayValue.loggerName						as [logger name]						,
flat.ArrayValue.parameters						as [parameters]							,
flat.ArrayValue.raw								as [raw]								,
flat.ArrayValue.severityLevel					as [severity level]						,

A.context.custom.dimensions						as [custom attributes]					,
A.context.custom.metrics						as [custom metrics]						,
A.context.data.eventTime						as [event time]							,
A.context.data.isSynthetic						as [is synthetic]						,
A.context.data.samplingRate						as [samplingRate]						,
A.context.device								as [device]								,
A.context.device.browser						as [browser]							,
A.context.device.browserVersion					as [browser version]					,
A.context.device.deviceModel					as [device model]						,
A.context.device.deviceName						as [device name]						,
A.context.device.id								as [device id]							,
A.context.device.locale							as [device locale]						,
A.context.device.network						as [device network]						,
A.context.device.oemName						as [device oem name]					,
A.context.device.osVersion						as [device os version]					,
A.context.device.roleInstance					as [device role instance]				,
A.context.device.roleName						as [device role name]					,
A.context.device.type							as [device type]						,
A.context.location								as [location]							,
A.context.location.city							as [location city]						,
A.context.location.continent					as [location continent]					,
A.context.location.country						as [location country]					,
A.context.location.province						as [location province]					,
A.context.location.clientip						as [ip address]							,
A.context.operation.id							as [operation id]						,
A.context.operation.name						as [operation name]						,
A.context.operation.parentId					as [parent id]							,
A.context.session.id							as [session id]							,
A.context.session.isFirst						as [session is first]					,
A.context.[user].accountAcquisitionDate			as [account aquisition date]			,
A.context.[user].anonAcquisitionDate			as [annoymous aquisition date]			,
A.context.[user].anonId							as [anonymous id]						,
A.context.[user].authAcquisitionDate			as [auth aquisition date]				,
A.context.[user].isAuthenticated				as [is authenticated]					,
A.internal.data.documentVersion					as [document version]					,
A.internal.data.id								as [data id]							,
'Trace'											as [eventtype]
INTO docdb
FROM messages A CROSS APPLY GetElements(A.[message]) as flat

--requests
SELECT   

flat.ArrayValue.count							as [count]								,
flat.ArrayValue.durationMetric.value			as [duration metric value]				,
flat.ArrayValue.id								as [id]									,
flat.ArrayValue.name							as [name]								,
flat.ArrayValue.responseCode					as [response code]						,
flat.ArrayValue.success							as [success]							,
flat.ArrayValue.url								as [url]								,
flat.ArrayValue.urlData.base					as [url data base]						,
flat.ArrayValue.urlData.hashTag					as [url data hash tag]					,
flat.ArrayValue.urlData.host					as [url data host]						,
A.context.custom.dimensions						as [custom attributes]					,
A.context.custom.metrics						as [custom metrics]						,
A.context.data.eventTime						as [event time]							,
A.context.data.isSynthetic						as [is synthetic]						,
A.context.data.samplingRate						as [samplingRate]						,
A.context.device								as [device]								,
A.context.device.browser						as [browser]							,
A.context.device.browserVersion					as [browser version]					,
A.context.device.deviceModel					as [device model]						,
A.context.device.deviceName						as [device name]						,
A.context.device.id								as [device id]							,
A.context.device.locale							as [device locale]						,
A.context.device.network						as [device network]						,
A.context.device.oemName						as [device oem name]					,
A.context.device.osVersion						as [device os version]					,
A.context.device.roleInstance					as [device role instance]				,
A.context.device.roleName						as [device role name]					,
A.context.device.type							as [device type]						,
A.context.location								as [location]							,
A.context.location.city							as [location city]						,
A.context.location.continent					as [location continent]					,
A.context.location.country						as [location country]					,
A.context.location.province						as [location province]					,
A.context.location.clientip						as [ip address]							,
A.context.operation.id							as [operation id]						,
A.context.operation.name						as [operation name]						,
A.context.operation.parentId					as [parent id]							,
A.context.session.id							as [session id]							,
A.context.session.isFirst						as [session is first]					,
A.context.[user].accountAcquisitionDate			as [account aquisition date]			,
A.context.[user].anonAcquisitionDate			as [annoymous aquisition date]			,
A.context.[user].anonId							as [anonymous id]						,
A.context.[user].authAcquisitionDate			as [auth aquisition date]				,
A.context.[user].isAuthenticated				as [is authenticated]					,
A.internal.data.documentVersion					as [document version]					,
A.internal.data.id								as [data id]							,
'Requests'										as [eventtype]
INTO docdb
FROM requests A CROSS APPLY GetElements(A.[request]) as flat

--pageviews
SELECT  


flat.ArrayValue.count							as [count]								,
flat.ArrayValue.durationMetric.value			as [duration metric value]				,
flat.ArrayValue.name							as [name]								,
flat.ArrayValue.url								as [url]								,
flat.ArrayValue.urlData.base					as [url data base]						,
flat.ArrayValue.urlData.hashTag					as [url data hash tag]					,
flat.ArrayValue.urlData.host 					as [url data host]						,

A.context.custom.dimensions						as [custom attributes]					,
A.context.custom.metrics						as [custom metrics]						,
A.context.data.eventTime						as [event time]							,
A.context.data.isSynthetic						as [is synthetic]						,
A.context.data.samplingRate						as [samplingRate]						,
A.context.device								as [device]								,
A.context.device.browser						as [browser]							,
A.context.device.browserVersion					as [browser version]					,
A.context.device.deviceModel					as [device model]						,
A.context.device.deviceName						as [device name]						,
A.context.device.id								as [device id]							,
A.context.device.locale							as [device locale]						,
A.context.device.network						as [device network]						,
A.context.device.oemName						as [device oem name]					,
A.context.device.osVersion						as [device os version]					,
A.context.device.roleInstance					as [device role instance]				,
A.context.device.roleName						as [device role name]					,
A.context.device.type							as [device type]						,
A.context.location								as [location]							,
A.context.location.city							as [location city]						,
A.context.location.continent					as [location continent]					,
A.context.location.country						as [location country]					,
A.context.location.province						as [location province]					,
A.context.location.clientip						as [ip address]							,
A.context.operation.id							as [operation id]						,
A.context.operation.name						as [operation name]						,
A.context.operation.parentId					as [parent id]							,
A.context.session.id							as [session id]							,
A.context.session.isFirst						as [session is first]					,
A.context.[user].accountAcquisitionDate			as [account aquisition date]			,
A.context.[user].anonAcquisitionDate			as [annoymous aquisition date]			,
A.context.[user].anonId							as [anonymous id]						,
A.context.[user].authAcquisitionDate			as [auth aquisition date]				,
A.context.[user].isAuthenticated				as [is authenticated]					,
A.internal.data.documentVersion					as [document version]					,
A.internal.data.id								as [data id]							,
'Page Views'									as [eventtype]
INTO docdb
FROM pageviews A CROSS APPLY GetElements(A.[view]) as flat