SET ANSI_NULLS              ON;
SET ANSI_PADDING            ON;
SET ANSI_WARNINGS           ON;
SET ANSI_NULL_DFLT_ON       ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER       ON;
go


CREATE TABLE [dbo].[configuration]
(
  id                     INT IDENTITY(1, 1) NOT NULL,
  configuration_group    VARCHAR(150) NOT NULL,
  configuration_subgroup VARCHAR(150) NOT NULL,
  name                   VARCHAR(150) NOT NULL,
  [value]                VARCHAR(max) NULL,
  visible                BIT NOT NULL DEFAULT 0
);


CREATE TABLE [dbo].[events] (
	[event name]							NVARCHAR(250) NULL,
	[event count]							int NULL,
	[event uri]								NVARCHAR(250) NULL,
	[event uri data base]					NVARCHAR(250) NULL,
	[event uri data host]					NVARCHAR(250) NULL,
	 --Common properties
	[custom attributes]						NVARCHAR(MAX) NULL,
	[custom metrics]						NVARCHAR(MAX) NULL,
	[event time]							datetime NOT NULL,
	[is synthetic]							int NULL,
	[samplingRate]							NVARCHAR(100) NULL,
	[device]								NVARCHAR(100) NULL,
	[browser]								NVARCHAR(100) NULL,
	[browser version]						NVARCHAR(100) NULL,
	[device model]							NVARCHAR(100) NULL,
	[device name]							NVARCHAR(100) NULL,
	[device id]								NVARCHAR(100) NULL,
	[device locale]							NVARCHAR(100) NULL,
	[device network]						NVARCHAR(100) NULL,
	[device oem name]						NVARCHAR(100) NULL,
	[device os version]						NVARCHAR(100) NULL,
	[device role instance]					NVARCHAR(100) NULL,
	[device role name]						NVARCHAR(100) NULL,
	[device type]							NVARCHAR(100) NULL,
	[location]								NVARCHAR(100) NULL,
	[location city]							NVARCHAR(100) NULL,
	[location continent]					NVARCHAR(100) NULL,
	[location country]						NVARCHAR(100) NULL,
	[location province]						NVARCHAR(100) NULL,
	[ip address]							NVARCHAR(100) NULL,
	[operation id]							NVARCHAR(100) NULL,
	[operation name]						NVARCHAR(100) NULL,
	[parent id]								NVARCHAR(100) NULL,
	[session id]							NVARCHAR(100) NULL,
	[session is first]						int NULL,
	[account aquisition date]				NVARCHAR(100) NULL,
	[annoymous aquisition date]				NVARCHAR(100) NULL,
	[anonymous id]							NVARCHAR(100) NULL,
	[auth aquisition date]					NVARCHAR(100) NULL,
	[is authenticated]						int NULL,
	[document version]						NVARCHAR(100) NULL,
	[data id]								NVARCHAR(100) NULL,
	[eventtype]							NVARCHAR(100) NULL
)

CREATE TABLE [dbo].exception (
	[assembly]								NVARCHAR(250) NULL,
	[count]									int NULL,
	[exception group]						NVARCHAR(250) NULL,
	[exception type]						NVARCHAR(250) NULL,
	[failed user code method]				NVARCHAR(250) NULL,
	[failed user code assembly]				NVARCHAR(250) NULL,
	[handled at]							NVARCHAR(250) NULL,
	[has full stack]						NVARCHAR(250) NULL,
	[id]									NVARCHAR(250) NULL,
	[method]								NVARCHAR(250) NULL,
	[message]								NVARCHAR(MAX) NULL,
	[outer exception message]				NVARCHAR(250) NULL,
	[outer exception thrown at assembly]	NVARCHAR(250) NULL,
	[outer exception thrown at method]		NVARCHAR(250) NULL,
	[outer exception type]					NVARCHAR(250) NULL,
	[outer id]								NVARCHAR(250) NULL,
	[parsed stack ]							NVARCHAR(MAX) NULL,
	[stack]									NVARCHAR(MAX) NULL,
	[type name]								NVARCHAR(250) NULL,

	 --Common properties
	[custom attributes]						NVARCHAR(MAX) NULL,
	[custom metrics]						NVARCHAR(MAX) NULL,
	[event time]							datetime NOT NULL,
	[is synthetic]							int NULL,
	[samplingRate]							NVARCHAR(100) NULL,
	[device]								NVARCHAR(100) NULL,
	[browser]								NVARCHAR(100) NULL,
	[browser version]						NVARCHAR(100) NULL,
	[device model]							NVARCHAR(100) NULL,
	[device name]							NVARCHAR(100) NULL,
	[device id]								NVARCHAR(100) NULL,
	[device locale]							NVARCHAR(100) NULL,
	[device network]						NVARCHAR(100) NULL,
	[device oem name]						NVARCHAR(100) NULL,
	[device os version]						NVARCHAR(100) NULL,
	[device role instance]					NVARCHAR(100) NULL,
	[device role name]						NVARCHAR(100) NULL,
	[device type]							NVARCHAR(100) NULL,
	[location]								NVARCHAR(100) NULL,
	[location city]							NVARCHAR(100) NULL,
	[location continent]					NVARCHAR(100) NULL,
	[location country]						NVARCHAR(100) NULL,
	[location province]						NVARCHAR(100) NULL,
	[ip address]							NVARCHAR(100) NULL,
	[operation id]							NVARCHAR(100) NULL,
	[operation name]						NVARCHAR(100) NULL,
	[parent id]								NVARCHAR(100) NULL,
	[session id]							NVARCHAR(100) NULL,
	[session is first]						int NULL,
	[account aquisition date]				NVARCHAR(100) NULL,
	[annoymous aquisition date]				NVARCHAR(100) NULL,
	[anonymous id]							NVARCHAR(100) NULL,
	[auth aquisition date]					NVARCHAR(100) NULL,
	[is authenticated]						int NULL,
	[document version]						NVARCHAR(100) NULL,
	[data id]								NVARCHAR(100) NULL,
	[eventtype]							NVARCHAR(100) NULL
)


CREATE TABLE [dbo].[trace] (
	[logger name]							NVARCHAR(250) NULL,
	[parameters]							NVARCHAR(250) NULL,
	[raw]									NVARCHAR(MAX) NULL,
	[severity level]						NVARCHAR(250) NULL,
	 --Common properties
	[custom attributes]						NVARCHAR(MAX) NULL,
	[custom metrics]						NVARCHAR(MAX) NULL,
	[event time]							datetime NOT NULL,
	[is synthetic]							int NULL,
	[samplingRate]							NVARCHAR(100) NULL,
	[device]								NVARCHAR(100) NULL,
	[browser]								NVARCHAR(100) NULL,
	[browser version]						NVARCHAR(100) NULL,
	[device model]							NVARCHAR(100) NULL,
	[device name]							NVARCHAR(100) NULL,
	[device id]								NVARCHAR(100) NULL,
	[device locale]							NVARCHAR(100) NULL,
	[device network]						NVARCHAR(100) NULL,
	[device oem name]						NVARCHAR(100) NULL,
	[device os version]						NVARCHAR(100) NULL,
	[device role instance]					NVARCHAR(100) NULL,
	[device role name]						NVARCHAR(100) NULL,
	[device type]							NVARCHAR(100) NULL,
	[location]								NVARCHAR(100) NULL,
	[location city]							NVARCHAR(100) NULL,
	[location continent]					NVARCHAR(100) NULL,
	[location country]						NVARCHAR(100) NULL,
	[location province]						NVARCHAR(100) NULL,
	[ip address]							NVARCHAR(100) NULL,
	[operation id]							NVARCHAR(100) NULL,
	[operation name]						NVARCHAR(100) NULL,
	[parent id]								NVARCHAR(100) NULL,
	[session id]							NVARCHAR(100) NULL,
	[session is first]						int NULL,
	[account aquisition date]				NVARCHAR(100) NULL,
	[annoymous aquisition date]				NVARCHAR(100) NULL,
	[anonymous id]							NVARCHAR(100) NULL,
	[auth aquisition date]					NVARCHAR(100) NULL,
	[is authenticated]						int NULL,
	[document version]						NVARCHAR(100) NULL,
	[data id]								NVARCHAR(100) NULL,
	[eventtype]							NVARCHAR(100) NULL
)

CREATE TABLE [dbo].[remote dependancy] (
	[async]									int NULL,
	[base name]								NVARCHAR(250) NULL,
	[command name]							NVARCHAR(250) NULL,
	[count]									int NULL,
	[dependancy type name]					NVARCHAR(250) NULL,
	[duration metric value]					int NULL,
	[id]									NVARCHAR(250) NULL,
	[name]									NVARCHAR(250) NULL,
	[result code]							NVARCHAR(250) NULL,
	[success]								int NULL,
	[type]									NVARCHAR(250) NULL,
	[url]									NVARCHAR(2000) NULL,
	[url data base]							NVARCHAR(250) NULL,
	[url data hash tag]						NVARCHAR(250) NULL,
	[url data host]							NVARCHAR(250) NULL,

	 --Common properties
	[custom attributes]						NVARCHAR(MAX) NULL,
	[custom metrics]						NVARCHAR(MAX) NULL,
	[event time]							datetime NOT NULL,
	[is synthetic]							int NULL,
	[samplingRate]							NVARCHAR(100) NULL,
	[device]								NVARCHAR(100) NULL,
	[browser]								NVARCHAR(100) NULL,
	[browser version]						NVARCHAR(100) NULL,
	[device model]							NVARCHAR(100) NULL,
	[device name]							NVARCHAR(100) NULL,
	[device id]								NVARCHAR(100) NULL,
	[device locale]							NVARCHAR(100) NULL,
	[device network]						NVARCHAR(100) NULL,
	[device oem name]						NVARCHAR(100) NULL,
	[device os version]						NVARCHAR(100) NULL,
	[device role instance]					NVARCHAR(100) NULL,
	[device role name]						NVARCHAR(100) NULL,
	[device type]							NVARCHAR(100) NULL,
	[location]								NVARCHAR(100) NULL,
	[location city]							NVARCHAR(100) NULL,
	[location continent]					NVARCHAR(100) NULL,
	[location country]						NVARCHAR(100) NULL,
	[location province]						NVARCHAR(100) NULL,
	[ip address]							NVARCHAR(100) NULL,
	[operation id]							NVARCHAR(100) NULL,
	[operation name]						NVARCHAR(100) NULL,
	[parent id]								NVARCHAR(100) NULL,
	[session id]							NVARCHAR(100) NULL,
	[session is first]						int NULL,
	[account aquisition date]				NVARCHAR(100) NULL,
	[annoymous aquisition date]				NVARCHAR(100) NULL,
	[anonymous id]							NVARCHAR(100) NULL,
	[auth aquisition date]					NVARCHAR(100) NULL,
	[is authenticated]						int NULL,
	[document version]						NVARCHAR(100) NULL,
	[data id]								NVARCHAR(100) NULL,
	[eventtype]							NVARCHAR(100) NULL
)

CREATE TABLE [dbo].[requests] (
	[count]									int NULL,
	[duration metric value]					int NULL,
	[id]									NVARCHAR(250) NULL,
	[name]									NVARCHAR(250) NULL,
	[response code]							int NULL,
	[success]								int NULL,
	[url]									NVARCHAR(2000) NULL,
	[url data base]							NVARCHAR(250) NULL,
	[url data hash tag]						NVARCHAR(250) NULL,
	[url data host]							NVARCHAR(250) NULL,

	 --Common properties
	[custom attributes]						NVARCHAR(MAX) NULL,
	[custom metrics]						NVARCHAR(MAX) NULL,
	[event time]							datetime NOT NULL,
	[is synthetic]							int NULL,
	[samplingRate]							NVARCHAR(100) NULL,
	[device]								NVARCHAR(100) NULL,
	[browser]								NVARCHAR(100) NULL,
	[browser version]						NVARCHAR(100) NULL,
	[device model]							NVARCHAR(100) NULL,
	[device name]							NVARCHAR(100) NULL,
	[device id]								NVARCHAR(100) NULL,
	[device locale]							NVARCHAR(100) NULL,
	[device network]						NVARCHAR(100) NULL,
	[device oem name]						NVARCHAR(100) NULL,
	[device os version]						NVARCHAR(100) NULL,
	[device role instance]					NVARCHAR(100) NULL,
	[device role name]						NVARCHAR(100) NULL,
	[device type]							NVARCHAR(100) NULL,
	[location]								NVARCHAR(100) NULL,
	[location city]							NVARCHAR(100) NULL,
	[location continent]					NVARCHAR(100) NULL,
	[location country]						NVARCHAR(100) NULL,
	[location province]						NVARCHAR(100) NULL,
	[ip address]							NVARCHAR(100) NULL,
	[operation id]							NVARCHAR(100) NULL,
	[operation name]						NVARCHAR(100) NULL,
	[parent id]								NVARCHAR(100) NULL,
	[session id]							NVARCHAR(100) NULL,
	[session is first]						int NULL,
	[account aquisition date]				NVARCHAR(100) NULL,
	[annoymous aquisition date]				NVARCHAR(100) NULL,
	[anonymous id]							NVARCHAR(100) NULL,
	[auth aquisition date]					NVARCHAR(100) NULL,
	[is authenticated]						int NULL,
	[document version]						NVARCHAR(100) NULL,
	[data id]								NVARCHAR(100) NULL,
	[eventtype]							NVARCHAR(100) NULL
)

CREATE TABLE [dbo].[page view performance] (
	[client process value]					int NULL,
	[name]									NVARCHAR(250) NULL,
	[network connection value]				int NULL,
	[recieve request value]					int NULL,
	[send request value]					int NULL,
	[total value]							int NULL,
	[url]									NVARCHAR(250) NULL,
	[url data base]							NVARCHAR(250) NULL,
	[url data hash tag]						NVARCHAR(250) NULL,
	[url data host]							NVARCHAR(250) NULL,
	[url data protocol]						NVARCHAR(250) NULL,

	 --Common properties
	[custom attributes]						NVARCHAR(MAX) NULL,
	[custom metrics]						NVARCHAR(MAX) NULL,
	[event time]							datetime NOT NULL,
	[is synthetic]							int NULL,
	[samplingRate]							NVARCHAR(100) NULL,
	[device]								NVARCHAR(100) NULL,
	[browser]								NVARCHAR(100) NULL,
	[browser version]						NVARCHAR(100) NULL,
	[device model]							NVARCHAR(100) NULL,
	[device name]							NVARCHAR(100) NULL,
	[device id]								NVARCHAR(100) NULL,
	[device locale]							NVARCHAR(100) NULL,
	[device network]						NVARCHAR(100) NULL,
	[device oem name]						NVARCHAR(100) NULL,
	[device os version]						NVARCHAR(100) NULL,
	[device role instance]					NVARCHAR(100) NULL,
	[device role name]						NVARCHAR(100) NULL,
	[device type]							NVARCHAR(100) NULL,
	[location]								NVARCHAR(100) NULL,
	[location city]							NVARCHAR(100) NULL,
	[location continent]					NVARCHAR(100) NULL,
	[location country]						NVARCHAR(100) NULL,
	[location province]						NVARCHAR(100) NULL,
	[ip address]							NVARCHAR(100) NULL,
	[operation id]							NVARCHAR(100) NULL,
	[operation name]						NVARCHAR(100) NULL,
	[parent id]								NVARCHAR(100) NULL,
	[session id]							NVARCHAR(100) NULL,
	[session is first]						int NULL,
	[account aquisition date]				NVARCHAR(100) NULL,
	[annoymous aquisition date]				NVARCHAR(100) NULL,
	[anonymous id]							NVARCHAR(100) NULL,
	[auth aquisition date]					NVARCHAR(100) NULL,
	[is authenticated]						int NULL,
	[document version]						NVARCHAR(100) NULL,
	[data id]								NVARCHAR(100) NULL,
	[eventtype]							NVARCHAR(100) NULL
)

CREATE TABLE [dbo].[page views] (
	[count]									int NULL,
	[duration metric value]					int NULL,
	[name]									NVARCHAR(250) NULL,
	[url]									NVARCHAR(250) NULL,
	[url data base]							NVARCHAR(250) NULL,
	[url data hash tag]						NVARCHAR(250) NULL,
	[url data host]							NVARCHAR(250) NULL,

	 --Common properties
	[custom attributes]						NVARCHAR(MAX) NULL,
	[custom metrics]						NVARCHAR(MAX) NULL,
	[event time]							datetime NOT NULL,
	[is synthetic]							int NULL,
	[samplingRate]							NVARCHAR(100) NULL,
	[device]								NVARCHAR(100) NULL,
	[browser]								NVARCHAR(100) NULL,
	[browser version]						NVARCHAR(100) NULL,
	[device model]							NVARCHAR(100) NULL,
	[device name]							NVARCHAR(100) NULL,
	[device id]								NVARCHAR(100) NULL,
	[device locale]							NVARCHAR(100) NULL,
	[device network]						NVARCHAR(100) NULL,
	[device oem name]						NVARCHAR(100) NULL,
	[device os version]						NVARCHAR(100) NULL,
	[device role instance]					NVARCHAR(100) NULL,
	[device role name]						NVARCHAR(100) NULL,
	[device type]							NVARCHAR(100) NULL,
	[location]								NVARCHAR(100) NULL,
	[location city]							NVARCHAR(100) NULL,
	[location continent]					NVARCHAR(100) NULL,
	[location country]						NVARCHAR(100) NULL,
	[location province]						NVARCHAR(100) NULL,
	[ip address]							NVARCHAR(100) NULL,
	[operation id]							NVARCHAR(100) NULL,
	[operation name]						NVARCHAR(100) NULL,
	[parent id]								NVARCHAR(100) NULL,
	[session id]							NVARCHAR(100) NULL,
	[session is first]						int NULL,
	[account aquisition date]				NVARCHAR(100) NULL,
	[annoymous aquisition date]				NVARCHAR(100) NULL,
	[anonymous id]							NVARCHAR(100) NULL,
	[auth aquisition date]					NVARCHAR(100) NULL,
	[is authenticated]						int NULL,
	[document version]						NVARCHAR(100) NULL,
	[data id]								NVARCHAR(100) NULL,
	[eventtype]							NVARCHAR(100) NULL
)